### ISSUE TITLE
[Bug] Server::getServerByTld() failed with unknown TLD

### ISSUE THREAD

**Issue by Aliance** [petk/phpwhois#5]
Hello. If I tried to execute `(new Whois('ANY_DOMAIN.website'))->lookup();`, this will cause a Type error in PHP

> PhpWhois\Server::getServerByTld(): Return value must be of type string, null returned

Because `getServerByTld` expect to be return only strings, but there is no `website` TLD into an array of known.
https://github.com/petk/phpwhois/blob/master/src/Server.php#L299-L302

Possible solution: add `??` operator to the method.

**Comment by Aliance** [comment]
The same for `.club` domains. @petk is that package abandoned or is there a possibility for the fix?

**Comment by petk** [comment]
Hello, thanks for reporting the issue. Sorry, I've missed this. Yes, this package is quite abandoned. :/

**Comment by Aliance** [comment]
@petk if I make a pr with a fix, will you merge it?
